server:
  port: 8080

spring:
  application:
    name: librasys
  datasource:
    url: jdbc:mysql://localhost:3306/librasys_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: kedar
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  mail:
    host: localhost
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970
  expiration: 86400000 # 24 hours

logging:
  level:
    com.librasys: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cache: TRACE
